services:
  web:
    build: 
      context: .
      target: prod
    container_name: jiujitsu-unicamp-web
    restart: unless-stopped
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jiujitsu.rule=Host(`jiujitsuunicamp.com.br`)"
      - "traefik.http.routers.jiujitsu.entrypoints=web"
      - "traefik.http.services.jiujitsu.loadbalancer.server.port=80"

networks:
  proxy_net:
    external: true
